package com.xresch.cfw.features.query.sources;

import java.text.ParseException;
import java.util.concurrent.LinkedBlockingQueue;

import com.google.gson.JsonArray;
import com.xresch.cfw._main.CFW;
import com.xresch.cfw.datahandling.CFWField;
import com.xresch.cfw.datahandling.CFWField.FormFieldType;
import com.xresch.cfw.datahandling.CFWObject;
import com.xresch.cfw.features.core.AutocompleteResult;
import com.xresch.cfw.features.query.CFWQuery;
import com.xresch.cfw.features.query.CFWQueryAutocompleteHelper;
import com.xresch.cfw.features.query.CFWQuerySource;
import com.xresch.cfw.features.query.EnhancedJsonObject;
import com.xresch.cfw.features.query.FeatureQuery;
import com.xresch.cfw.features.usermgmt.User;
import com.xresch.cfw.utils.CFWRandom;

/**************************************************************************************************************
 * 
 * @author Reto Scheiwiller, (c) Copyright 2022 
 * @license MIT-License
 **************************************************************************************************************/
public class CFWQuerySourceRandom extends CFWQuerySource {

	/******************************************************************
	 *
	 ******************************************************************/
	public CFWQuerySourceRandom(CFWQuery parent) {
		super(parent);
	}

	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public String uniqueName() {
		return "random";
	}

	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public String descriptionShort() {
		return "Creates random person data useful for training, demostration and testing.";
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public String descriptionTime() {
		return "Time values are generated by this source based on the selected timeframe.";
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public String descriptionHTML() {
		return CFW.Files.readPackageResource(FeatureQuery.PACKAGE_MANUAL+".sources", "source_random.html");
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public String descriptionRequiredPermission() {
		return "None";
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public boolean hasPermission(User user) {
		return true;
	}
	
	/***********************************************************************************************
	 * 
	 ***********************************************************************************************/
	@Override
	public void autocomplete(AutocompleteResult result, CFWQueryAutocompleteHelper helper) {
		// do nothing
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public CFWObject getParameters() {
		return new CFWObject()
			.addField(
				CFWField.newInteger(FormFieldType.NUMBER, "records")
					.setDescription("Number of records to generate. (Default: 1000)")
					.setValue(1000)
			)
			.addField(
					CFWField.newString(FormFieldType.TEXT, "type")
						.setDescription("The type of data to generate, one of: 'default' | 'numbers' | 'arrays' | 'series' | 'various' ")
						.setValue("default")
				)
		;
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public void parametersPermissionCheck(CFWObject parameters) throws ParseException {
		//do nothing
	}
	
	/******************************************************************
	 *
	 ******************************************************************/
	@Override
	public void execute(CFWObject parameters, LinkedBlockingQueue<EnhancedJsonObject> outQueue, long earliestMillis, long latestMillis, int limit) throws Exception {
		
		int records = (int)parameters.getField("records").getValue();
		String type = (String)parameters.getField("type").getValue();

		long earliest = this.getParent().getContext().getEarliestMillis();
		long latest = this.getParent().getContext().getLatestMillis();
		long diff = latest - earliest;
		long diffStep = diff / records;
		
		// if not inside for to increase perofmrnace
		if(type.equals("default")) {
			for(int i = 0; i < records; i++) {
				
				EnhancedJsonObject person = new EnhancedJsonObject( CFWRandom.randomJSONObjectMightyPerson(4) );
				person.addProperty("INDEX", i );
				person.addProperty("TIME", earliest +(i * diffStep));
				outQueue.add(person);
				
				if( isLimitReached(limit, i)) { break; }
			}
		}else if(type.equals("numbers")) {
			
			for(int i = 0; i < records; i++) {
				
				EnhancedJsonObject object = new EnhancedJsonObject( CFWRandom.randomJSONObjectNumberData(0) );
				object.addProperty("TIME", earliest +(i * diffStep));
				outQueue.add(object);
				
				if( isLimitReached(limit, i)) { break; }
			}
		}else if(type.equals("arrays")) {
			
			for(int i = 0; i < records; i++) {
				
				EnhancedJsonObject object = new EnhancedJsonObject( CFWRandom.randomJSONObjectArrayData(0) );
				object.addProperty("TIME", earliest +(i * diffStep));
				outQueue.add(object);
				
				if( isLimitReached(limit, i)) { break; }
			}
		}else if(type.equals("series")) {
			
			JsonArray array = CFW.Random.randomJSONArrayOfSeriesData(3, records, earliest, latest);
			
			for(int i = 0; i < array.size(); i++) {
				
				EnhancedJsonObject object = new EnhancedJsonObject(array.get(i).getAsJsonObject());
				outQueue.add(object);
				
				if( isLimitReached(limit, i)) { break; }
			}
		}else if(type.equals("various")) {
			
			for(int i = 0; i < records; i++) {
				
				EnhancedJsonObject object = new EnhancedJsonObject( CFWRandom.randomJSONObjectVariousData(0) );
				object.addProperty("TIME", earliest +(i * diffStep));
				outQueue.add(object);
				
				if( isLimitReached(limit, i)) { break; }
			}
		}
		

	}

}
