SELECT COUNT(*) AS COUNT
FROM
	CFW_QUERY_STORED
WHERE
	PK_ID = ?
	AND (
		FK_ID_OWNER = ?
		OR (
		  IS_SHARED = TRUE
		  AND ( JSON_SHARE_WITH_USERS IS NULL
		    OR JSON_SHARE_WITH_USERS = '{}'
		  )
		  AND ( JSON_SHARE_WITH_GROUPS IS NULL
		    OR JSON_SHARE_WITH_GROUPS = '{}'
		  )
		)
		OR (IS_SHARED = TRUE
		  AND JSON_SHARE_WITH_USERS LIKE ? 
		)
		OR JSON_EDITORS LIKE ?
	);