SELECT T.PK_ID
	, T.NAME
	, T.QUERY
	, T.QUERY_PARAMS_DEFINED
	, T.QUERY_PARAMS
	, T.CHECK_PERMISSIONS
	, T.DESCRIPTION
	, T.TAGS
	, (SELECT USERNAME FROM CFW_USER U WHERE U.PK_ID = T.FK_ID_OWNER) AS OWNER
FROM
	CFW_QUERY_STORED T
WHERE
	T.IS_ARCHIVED = 0
	AND (
		(IS_SHARED = TRUE
		  AND ( JSON_SHARE_WITH_USERS IS NULL
		    OR JSON_SHARE_WITH_USERS = '{}'
		    OR FK_ID_OWNER = ? 
		  )
		  AND ( JSON_SHARE_WITH_GROUPS IS NULL
		    OR JSON_SHARE_WITH_GROUPS = '{}'
		    OR FK_ID_OWNER = ? 
		  )
		)
		OR (IS_SHARED = TRUE
		    AND JSON_SHARE_WITH_USERS LIKE ? )
		OR JSON_EDITORS LIKE ? 
	)