SELECT * FROM (SELECT 
	'WEEK' AS "SCOPE",
	PK_ID 
FROM CFW_DATE D
WHERE 
	WEEK_OF_YEAR = (SELECT WEEK_OF_YEAR FROM CFW_DATE WHERE PK_ID = ? )
	AND "YEAR" = (SELECT "YEAR" FROM CFW_DATE WHERE PK_ID = ? )
ORDER BY PK_ID DESC 
LIMIT 1 )
UNION
SELECT * FROM (SELECT 
	'MONTH' AS "SCOPE",
	PK_ID 
FROM CFW_DATE D
WHERE 
	"MONTH" = (SELECT "MONTH" FROM CFW_DATE WHERE PK_ID = ? )
	AND "YEAR" = (SELECT "YEAR" FROM CFW_DATE WHERE PK_ID = ? )
ORDER BY PK_ID DESC 
LIMIT 1)
UNION
SELECT * FROM (SELECT 
	'QUARTER' AS "SCOPE",
	PK_ID 
FROM CFW_DATE D
WHERE 
	"QUARTER_OF_YEAR" = (SELECT "QUARTER_OF_YEAR" FROM CFW_DATE WHERE PK_ID = ? )
	AND "YEAR" = (SELECT "YEAR" FROM CFW_DATE WHERE PK_ID = ? )
ORDER BY PK_ID DESC 
LIMIT 1)
UNION
SELECT * FROM (SELECT 
	'YEAR' AS "SCOPE",
	PK_ID 
FROM CFW_DATE D
WHERE 
	"YEAR" = (SELECT "YEAR" FROM CFW_DATE WHERE PK_ID = ? )
ORDER BY PK_ID DESC 
LIMIT 1)