SELECT P.PK_ID, P.ACTION_NAME, P.API_NAME, GP.FK_ID_TOKEN AS TOKEN_ID
FROM CFW_APITOKEN_PERMISSION P
LEFT JOIN CFW_APITOKEN_PERMISSION_MAP AS GP 
ON GP.FK_ID_PERMISSION = P.PK_ID
AND GP.FK_ID_TOKEN = ?
ORDER BY P.API_NAME, P.ACTION_NAME;
