SELECT P.PK_ID, P.ACTION_NAME, P.API_NAME, GP.FK_ID_TOKEN AS TOKEN_ID
FROM CFW_APITOKEN_PERMISSION P
JOIN CFW_APITOKEN_PERMISSION_MAP AS GP 
ON GP.FK_ID_PERMISSION = P.PK_ID
JOIN CFW_APITOKEN AS A
ON GP.FK_ID_TOKEN = A.PK_ID
AND A.TOKEN = ?;