/* ====== Update Table CFW_DASHBOARD_WIDGET ====== */
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'THRESHOLD_EXCELLENT', 'THRESHOLD_GREEN')  WHERE JSON_SETTINGS LIKE '%THRESHOLD_EXCELLENT%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'THRESHOLD_GOOD', 'THRESHOLD_LIMEGREEN')   WHERE JSON_SETTINGS LIKE '%THRESHOLD_GOOD%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'THRESHOLD_WARNING', 'THRESHOLD_YELLOW')   WHERE JSON_SETTINGS LIKE '%THRESHOLD_WARNING%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'THRESHOLD_EMERGENCY', 'THRESHOLD_ORANGE') WHERE JSON_SETTINGS LIKE '%THRESHOLD_EMERGENCY%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'THRESHOLD_DANGER', 'THRESHOLD_RED') 	  WHERE JSON_SETTINGS LIKE '%THRESHOLD_DANGER%';

UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'threshold_excellent', 'THRESHOLD_GREEN')  WHERE JSON_SETTINGS LIKE '%threshold_excellent%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'threshold_good', 'THRESHOLD_LIMEGREEN')   WHERE JSON_SETTINGS LIKE '%threshold_good%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'threshold_warning', 'THRESHOLD_YELLOW')   WHERE JSON_SETTINGS LIKE '%threshold_warning%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'threshold_emergency', 'THRESHOLD_ORANGE') WHERE JSON_SETTINGS LIKE '%threshold_emergency%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'threshold_danger', 'THRESHOLD_RED') 	  WHERE JSON_SETTINGS LIKE '%threshold_danger%';

UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'cfw-excellent', 'cfw-green') 	WHERE JSON_SETTINGS LIKE '%cfw-excellent%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'cfw-good', 'cfw-limegreen')  	WHERE JSON_SETTINGS LIKE '%cfw-good%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'cfw-warning', 'cfw-yellow')  	WHERE JSON_SETTINGS LIKE '%cfw-warning%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'cfw-emergency', 'cfw-orange')  	WHERE JSON_SETTINGS LIKE '%cfw-emergency%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_SETTINGS = REPLACE(JSON_SETTINGS, 'cfw-danger', 'cfw-red')  		WHERE JSON_SETTINGS LIKE '%cfw-danger%';

UPDATE CFW_DASHBOARD_WIDGET SET JSON_TASK_PARAMETERS = REPLACE(JSON_TASK_PARAMETERS, '"ALERT_THRESHOLD":"EXCELLENT"', '"ALERT_THRESHOLD":"GREEN"') 	WHERE JSON_TASK_PARAMETERS LIKE '%:"EXCELLENT"%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_TASK_PARAMETERS = REPLACE(JSON_TASK_PARAMETERS, '"ALERT_THRESHOLD":"GOOD"', '"ALERT_THRESHOLD":"LIMEGREEN"') 	WHERE JSON_TASK_PARAMETERS LIKE '%:"GOOD"%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_TASK_PARAMETERS = REPLACE(JSON_TASK_PARAMETERS, '"ALERT_THRESHOLD":"WARNING"', '"ALERT_THRESHOLD":"YELLOW"') 	WHERE JSON_TASK_PARAMETERS LIKE '%:"WARNING"%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_TASK_PARAMETERS = REPLACE(JSON_TASK_PARAMETERS, '"ALERT_THRESHOLD":"EMERGENCY"', '"ALERT_THRESHOLD":"ORANGE"') WHERE JSON_TASK_PARAMETERS LIKE '%:"EMERGENCY"%';
UPDATE CFW_DASHBOARD_WIDGET SET JSON_TASK_PARAMETERS = REPLACE(JSON_TASK_PARAMETERS, '"ALERT_THRESHOLD":"DANGER"', '"ALERT_THRESHOLD":"RED"') 		WHERE JSON_TASK_PARAMETERS LIKE '%:"DANGER"%';

/* ====== Update Table CFW_JOB ====== */
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'THRESHOLD_EXCELLENT', 'THRESHOLD_GREEN')  	WHERE JSON_PROPERTIES LIKE '%THRESHOLD_EXCELLENT%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'THRESHOLD_GOOD', 'THRESHOLD_LIMEGREEN') 		WHERE JSON_PROPERTIES LIKE '%THRESHOLD_GOOD%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'THRESHOLD_WARNING', 'THRESHOLD_YELLOW') 		WHERE JSON_PROPERTIES LIKE '%THRESHOLD_WARNING%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'THRESHOLD_EMERGENCY', 'THRESHOLD_ORANGE') 	WHERE JSON_PROPERTIES LIKE '%THRESHOLD_EMERGENCY%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'THRESHOLD_DANGER', 'THRESHOLD_RED') 			WHERE JSON_PROPERTIES LIKE '%THRESHOLD_DANGER%';

UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'threshold_excellent', 'THRESHOLD_GREEN')  WHERE JSON_PROPERTIES LIKE '%threshold_excellent%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'threshold_good', 'THRESHOLD_LIMEGREEN')   WHERE JSON_PROPERTIES LIKE '%threshold_good%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'threshold_warning', 'THRESHOLD_YELLOW')   WHERE JSON_PROPERTIES LIKE '%threshold_warning%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'threshold_emergency', 'THRESHOLD_ORANGE') WHERE JSON_PROPERTIES LIKE '%threshold_emergency%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, 'threshold_danger', 'THRESHOLD_RED') 	  WHERE JSON_PROPERTIES LIKE '%threshold_danger%';

UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, '"ALERT_THRESHOLD":"EXCELLENT"', '"ALERT_THRESHOLD":"GREEN"')		WHERE JSON_PROPERTIES LIKE '%:"EXCELLENT"%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, '"ALERT_THRESHOLD":"GOOD"', '"ALERT_THRESHOLD":"LIMEGREEN"')		WHERE JSON_PROPERTIES LIKE '%:"GOOD"%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, '"ALERT_THRESHOLD":"WARNING"', '"ALERT_THRESHOLD":"YELLOW"')		WHERE JSON_PROPERTIES LIKE '%:"WARNING"%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, '"ALERT_THRESHOLD":"EMERGENCY"', '"ALERT_THRESHOLD":"ORANGE"') 	WHERE JSON_PROPERTIES LIKE '%:"EMERGENCY"%';
UPDATE CFW_JOB SET JSON_PROPERTIES = REPLACE(JSON_PROPERTIES, '"ALERT_THRESHOLD":"DANGER"', '"ALERT_THRESHOLD":"RED"')			WHERE JSON_PROPERTIES LIKE '%:"DANGER"%';

