SELECT 
	SQL_STATEMENT AS STATEMENT, 
	EXECUTION_COUNT AS EXEC_COUNT, 
	ROUND(CUMULATIVE_EXECUTION_TIME,2) AS EXEC_TIME_TOTAL, 
	ROUND(MIN_EXECUTION_TIME,2) AS EXEC_TIME_MIN, 
	ROUND(AVERAGE_EXECUTION_TIME,2) AS EXEC_TIME_AVG, 
	ROUND(MAX_EXECUTION_TIME,2) AS EXEC_TIME_MAX, 
	ROUND(STD_DEV_EXECUTION_TIME,2) AS EXEC_TIME_STD_DEV, 
	MIN_ROW_COUNT AS ROW_COUNT_MIN, 
	ROUND(AVERAGE_ROW_COUNT,2) AS ROW_COUNT_AVG, 
	MAX_ROW_COUNT AS ROW_COUNT_MAX, 
	CUMULATIVE_ROW_COUNT AS ROW_COUNT_TOTAL, 
	ROUND(STD_DEV_ROW_COUNT,2) AS ROW_COUNT_STD_DEV
FROM INFORMATION_SCHEMA.QUERY_STATISTICS
ORDER BY EXEC_TIME_TOTAL DESC;