SELECT * FROM (   
	SELECT D.NAME AS DASHBOARD, G.NAME AS GROUPNAME, 
	(
		0 < (
			SELECT COUNT(*) FROM CFW_DASHBOARD X
			WHERE D.JSON_SHARE_WITH_GROUPS LIKE CONCAT('%', G.PK_ID, '%')
		)
	) AS VIEWER_BY_GROUP,
	(
		0 < (
			SELECT COUNT(*) FROM CFW_DASHBOARD Y
			WHERE D.JSON_EDITOR_GROUPS LIKE CONCAT('%', G.PK_ID, '%')
		)
	) AS EDITOR_BY_GROUP
	FROM CFW_USER U
	LEFT JOIN CFW_USER_ROLE_MAP AS UG ON UG.FK_ID_USER = U.PK_ID 
	LEFT JOIN CFW_ROLE AS G ON UG.FK_ID_ROLE = G.PK_ID 
	LEFT JOIN CFW_DASHBOARD AS D ON 1 = 1
	WHERE U.PK_ID = ?
	AND G.IS_GROUP = TRUE
	ORDER BY LOWER(D.NAME)
) WHERE 
	VIEWER_BY_GROUP = TRUE 
 OR EDITOR_BY_GROUP = TRUE