SELECT T.* 
	, (SELECT USERNAME FROM CFW_USER U WHERE U.PK_ID = T.FK_ID_USER) AS OWNER
	, TRUE AS IS_FAVED
FROM CFW_DASHBOARD T 
JOIN CFW_DASHBOARD_FAVORITE_MAP M
	ON T.PK_ID = M.FK_ID_DASHBOARD 
WHERE M.FK_ID_USER = ?
	AND T.VERSION = 0
ORDER BY LOWER(T.NAME)