SELECT T.PK_ID
	, T.NAME
	, T.DESCRIPTION
	, T.TAGS
	, (SELECT USERNAME FROM CFW_USER WHERE PK_ID = FK_ID_USER) AS OWNER
	, (SELECT COUNT(*) FROM CFW_DASHBOARD_FAVORITE_MAP M WHERE M.FK_ID_USER = ? AND M.FK_ID_DASHBOARD = T.PK_ID) > 0 AS IS_FAVED
FROM
	CFW_DASHBOARD T
WHERE
	(IS_SHARED = TRUE
	  AND ( JSON_SHARE_WITH_USERS IS NULL
	    OR JSON_SHARE_WITH_USERS = '{}'
	    OR FK_ID_USER = ? 
	  )
	  AND ( JSON_SHARE_WITH_GROUPS IS NULL
	    OR JSON_SHARE_WITH_GROUPS = '{}'
	    OR FK_ID_USER = ? 
	  )
	)
	OR (IS_SHARED = TRUE
	    AND JSON_SHARE_WITH_USERS LIKE ? )
	OR JSON_EDITORS LIKE ?  