/***********************************************
 * 
 ***********************************************/
SELECT DISTINCT
	  U.PK_ID
	, U.USERNAME
	, U.FIRSTNAME
	, U.LASTNAME
	, U.EMAIL
FROM CFW_USER U
LEFT JOIN (
	SELECT DISTINCT 
		  UM.FK_ID_USER AS "UM"
		, AM.FK_ID_USER AS "AM"
		, UG.FK_ID_USER AS "UG"
		, AG.FK_ID_USER AS "AG"
	FROM CFW_SPACES O
	-- Assigned User
	LEFT JOIN CFW_SPACES_USER_MAP UM 
		ON UM.FK_ID_SPACE = O.PK_ID 
	-- Admin User
	LEFT JOIN CFW_SPACES_ADMIN_MAP AM 
		ON AM.FK_ID_SPACE = O.PK_ID 
	-- By User Groups
	LEFT JOIN (
		SELECT FK_ID_SPACE, URM.FK_ID_USER
		FROM CFW_SPACES_USERGROUPS_MAP UGM 
		JOIN CFW_USER_ROLE_MAP URM
		  ON URM.FK_ID_ROLE = UGM.FK_ID_ROLE
	) UG 
		ON UG.FK_ID_SPACE = O.PK_ID 
	-- By Admin Groups
	LEFT JOIN (
		SELECT FK_ID_SPACE, URM.FK_ID_USER
		FROM CFW_SPACES_ADMINGROUPS_MAP AGM 
		JOIN CFW_USER_ROLE_MAP URM
		  ON URM.FK_ID_ROLE = AGM.FK_ID_ROLE
	) AG 
		ON AG.FK_ID_SPACE = O.PK_ID 
	WHERE O.H_ROOT = (SELECT H_ROOT FROM CFW_SPACES S WHERE S.PK_ID = ? ) -- selected Space
)
WHERE U.PK_ID = UM
   OR U.PK_ID = AM
   OR U.PK_ID = AG
   OR U.PK_ID = UG 
   AND (
   		  U.USERNAME LIKE ?
   	   OR U.FIRSTNAME LIKE ?
   	   OR U.LASTNAME LIKE ?
   )
   AND NOT U.PK_ID = ?
LIMIT ?	
