SELECT u.PK_ID AS USER_ID, u.USERNAME, u.FIRSTNAME, u.LASTNAME, u.EMAIL, urm.IS_DELETABLE AS IS_REMOVABLE
FROM CFW_ROLE r
JOIN CFW_USER_ROLE_MAP urm
ON urm.FK_ID_ROLE = r.PK_ID
JOIN CFW_USER u
ON urm.FK_ID_USER = u.PK_ID
WHERE urm.FK_ID_ROLE = ?
ORDER BY u.USERNAME;