SELECT DISTINCT 
	O.FK_ID_SPACE,
	( SELECT ABBREVIATION FROM CFW_SPACES AS S WHERE S.PK_ID = O.FK_ID_SPACE ) AS SPACE,
	NAME,
	(O.FK_ID_OWNER = ?) AS IS_OWNER, 
	(
	  IS_SHARED = TRUE
	  AND ( JSON_SHARE_WITH_USERS IS NULL
	    OR JSON_SHARE_WITH_USERS = '{}'
	  )
	  AND ( JSON_SHARE_WITH_GROUPS IS NULL
	    OR JSON_SHARE_WITH_GROUPS = '{}'
	  )
	) AS SHARED_GLOBAL,
	(
		IS_SHARED = TRUE
		AND JSON_SHARE_WITH_USERS LIKE ?
	) AS SHARED_WITH_USER,
	(O.JSON_EDITORS LIKE ? ) AS IS_EDITOR
	, CASE WHEN UG.FK_ID_USER = ? THEN TRUE ELSE FALSE END AS USER_BY_GROUP
	, CASE WHEN AG.FK_ID_USER = ? THEN TRUE ELSE FALSE END AS EDITOR_BY_GROUP
FROM {tablename} O
-- Assigned User
LEFT JOIN {tablename}_SHAREDUSER_MAP U 
	ON U.{foreignKeyName} = O.PK_ID 
-- Admin User
LEFT JOIN {tablename}_EDITORS_MAP A 
	ON A.{foreignKeyName} = O.PK_ID 
-- By User Groups
LEFT JOIN (
	SELECT {foreignKeyName}, URM.FK_ID_USER
	FROM {tablename}_SHAREDGROUPS_MAP UGM 
	JOIN CFW_USER_ROLE_MAP URM
	  ON URM.FK_ID_ROLE = UGM.FK_ID_ROLE
) UG 
	ON UG.{foreignKeyName} = O.PK_ID 
-- By Admin Groups
LEFT JOIN (
	SELECT {foreignKeyName}, URM.FK_ID_USER
	FROM {tablename}_EDITORGROUPS_MAP AGM 
	JOIN CFW_USER_ROLE_MAP URM
	  ON URM.FK_ID_ROLE = AGM.FK_ID_ROLE
) AG 
	ON AG.{foreignKeyName} = O.PK_ID 
WHERE ( O.IS_SHARED IS TRUE
  OR ( O.FK_ID_OWNER = ? 
     OR U.FK_ID_USER = ?
     OR A.FK_ID_USER = ?
     OR UG.FK_ID_USER = ?
     OR AG.FK_ID_USER = ?  
  )
  )