###################################################################################################
#                                   !!!!!!!!!!!!!!!!!
#                                   !!! IMPORTANT !!!
#                                   !!!!!!!!!!!!!!!!!
# ONLY CHANGE THE SALT STRINGS IN THIS FILE RIGHT AFTER INSTALLATION! 
# MAKE A BACKUP OF THIS FILE IF YOU EVER CHANGE ITS VALUES! 
# IF YOU LOSE YOUR CUSTOMIZED FILE, YOUR APPLICATION WON'T BE ABLE TO DECRYPT YOUR DATA ANYMORE.
# 
# This file is created on application startup with default values, which also ensures backward
# compatibility with older versions.
# 
###################################################################################################
saltCredentialsAccount=CredentialsAccount-Default-Salt
saltCredentialsPW=CredentialsPW-Default-Salt
saltCredentialsToken=CredentialsToken-Default-Salt
saltCredentialsSecret=CredentialsSecret-Default-Salt
saltCredentialsDomain=CredentialsDomain-Default-Salt
saltCredentialsHostname=CredentialsHostname-Default-Salt
saltCredentialsUrl=CredentialsUrl-Default-Salt
saltCredentialsData=CredentialsData-Default-Salt
saltCredentialsCustom=CredentialsCustom-Default-Salt
saltDBJDBC=genericjdbc_DB_PW_Salt
saltDBMySQL=mysql_DB_PW_Salt
saltDBMSSQL=mssql_DB_PW_Salt
saltDBOracle=oracle_DB_PW_Salt
saltDBPostgres=postgres_DB_PW_Salt
saltDefaultA=salt-default-A-0;6d?{3[H1hCiCCS1GK)P=[Q[d*A/ta:)n86UwG[(7-6ut=VEN*}BF6M1Y5>c?[l-7NQ9c&g[a1*e]j3cN47{_y5-8&%m:}K=M%???1F&/JMs))1ac9H1d8/>{2OZUoe
saltDefaultB=salt-default-B-s)Ek<oQ0g>[[e-!o27U=<ASww/{I+3/B.2Fi{]z%76FH3Ai9{7KN{9Zj:7+(++==Vy+pq4.?x>.*Wjq>;.=?]30M772).aNn-3<%:H%A;82%/G!?/N0d4?_B3DA]]7//
saltDefaultC=salt-default-C-YBK!Ho_}77go.&S}5h:e9d2{/373rX}z+.KbEN?X(&&E/<O5%3x[jx[iN,q+_(:SQ6Qd%.ks*N.L7oF:-,3=Z*VE0brsUT0!V[1<%NM4:[CGr7=/}(ga=(Fyz*7b5}qf
saltDefaultD=salt-default-D-JZ1U:XKfZml>]*/hl?CCb6}&zmd!+)?VV&H<iz:027K=3V?Tp7Dbu7lnEY:5QG5u&8s3:Y-qJ3%mMr)U?/*D4/lVOI)Ik}{PjAF4!u!%?nj3&kuVrLw(EQ90-k[Cw}6(
saltDefaultE=salt-default-E-TOwL<?41ZI]-L%6D&OC<Job</wT?+rH9-:C(3H<l?p:+bbPjhW&!m46R]9E.,KPMC=bgJ9qq4W:}%T4lz7n[.E&S1u/jm59z7!!wX5{q!zI(0VIY}hNY]i3<v]+R+{YQ
saltDefaultF=salt-default-F->15f-*?/x734X33JH?8][44VuA,s6K=g)9Q5-N*%0b!TT?kuckTH)JZv+R<mkQTM8(xyef1b>oKYbc+);LP+O8.?U8(sN%A2+(8/3m{NIeXY+e_;vYsf[,Tt1,Lr*!--
saltDefaultG=salt-default-G-E{yrd+I3h&]W}3TwG<%[mV{vx9LA-x(;,o!&?Sh[H/u4F-23)f{1+zV((_-,ItR>W(7(E.V?0q/pt-%0.*t<A?qP]e1?2JN6LOre0[]69=rAN}>-3154KNAdS>4>1}%(
saltDefaultH=salt-default-H-0f:&:q2ZZa%bf)i}2]18>?o4B>Wvl{y:9;1lF6N_9+L:Y[8y??PMaV11-1nN0{}2t!>,3U8<!U+/.2:lW>QpPS%nUT/I?,RU:,!]+}&tnb}rlI(I]}}X;9(+<_)2ZBs%
