SELECT Count(*) AS COUNT, MAX(SEVERITY) as SEVERITY
FROM (
	SELECT (
		CASE cn.MESSAGE_TYPE 
			WHEN 'INFO' THEN 1
			WHEN 'SUCCESS' THEN 2 
			WHEN 'WARNING' THEN 3 
			WHEN 'ERROR' THEN 4 
		END
	) AS SEVERITY
	FROM CFW_NOTIFICATION cn 
	WHERE cn.FK_ID_USER = ?
	AND cn.IS_READ = FALSE
)
