SELECT DISTINCT 
	  O.PK_ID
	, O.ABBREVIATION
	, O.NAME
	, O.H_DEPTH 
	, O.H_PARENT
	, O.H_LINEAGE
FROM CFW_SPACES O
-- Assigned User
LEFT JOIN CFW_SPACES_USER_MAP U 
	ON U.FK_ID_SPACE = O.PK_ID 
-- Admin User
LEFT JOIN CFW_SPACES_EDITOR_MAP A 
	ON A.FK_ID_SPACE = O.PK_ID 
-- By User Groups
LEFT JOIN (
	SELECT FK_ID_SPACE, URM.FK_ID_USER
	FROM CFW_SPACES_USERGROUPS_MAP UGM 
	JOIN CFW_USER_ROLE_MAP URM
	  ON URM.FK_ID_ROLE = UGM.FK_ID_ROLE
) UG 
	ON UG.FK_ID_SPACE = O.PK_ID 
-- By Admin Groups
LEFT JOIN (
	SELECT FK_ID_SPACE, URM.FK_ID_USER
	FROM CFW_SPACES_EDITORGROUPS_MAP AGM 
	JOIN CFW_USER_ROLE_MAP URM
	  ON URM.FK_ID_ROLE = AGM.FK_ID_ROLE
) AG 
	ON AG.FK_ID_SPACE = O.PK_ID 
WHERE O.IS_ENABLED IS TRUE
  AND ( U.FK_ID_USER = ? 
     OR A.FK_ID_USER = ?
     OR UG.FK_ID_USER = ?
     OR AG.FK_ID_USER = ?
  ) 
ORDER BY LOWER(O.NAME)