SELECT DISTINCT 
	O.PK_ID
	, O.ABBREVIATION
	, O.NAME
	, O.H_LINEAGE[1] AS PARENTID
	FROM CFW_SPACES O
	JOIN CFW_SPACES_USER_MAP M ON M.FK_ID_SPACE = O.PK_ID 
	WHERE M.FK_ID_USER = ?
	  AND ARRAY_LENGTH(O.H_LINEAGE) > 0 
	ORDER BY LOWER(O.NAME)
UNION
SELECT P.PK_ID, P.ABBREVIATION, P.NAME
FROM CFW_SPACES P 
LEFT JOIN CFW_SPACES_ADMIN_MAP A ON A.FK_ID_SPACE = P.PK_ID 
	WHERE A.FK_ID_USER = ?